apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: userservice.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: userservice-api
                port:
                  number: 80
